version: '2'
services:

  mysql:
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_DATABASE=app"
    ports:
      - "33061:3306"
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql



  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm/php-fpm.docker
    volumes:
      - ./:/var/www
#    тут добавляем в папку контейнера /usr/local/etc/php/custom.d содержимое ./docker/php-ini
      - ./docker/php-ini:/usr/local/etc/php/custom.d
    links:
      - mysql
      - redis
      - elasticsearch
    environment:
#    тут добавляем в php.ini контейнера нужные дополнения из /usr/local/etc/php/custom.d
      - "PHP_INI_SCAN_DIR=/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
      - "PHP_IDE_CONFIG=serverName=docker_server"
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis"
      - "ELASTICSEARCH_HOST=elasticsearch:9200"




  php-cli:
    build:
      context: ./
      dockerfile: docker/php-fpm/php-fpm.docker
    volumes:
      - ./:/var/www
#    тут добавляем в папку контейнера /usr/local/etc/php/custom.d содержимое ./docker/php-ini
      - ./docker/php-ini:/usr/local/etc/php/custom.d
    links:
      - mysql
      - redis
      - elasticsearch
    environment:
      - "PHP_INI_SCAN_DIR=/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
      - "PHP_IDE_CONFIG=serverName=docker_server"
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis"
      - "ELASTICSEARCH_HOST=elasticsearch:9200"


  nginx:
    build:
      context: ./
      dockerfile: docker/nginx.docker
    volumes:
      - ./:/var/www
      - ./docker/nginx/ssl:/etc/nginx/ssl
    ports:
      - "8080:443"
    links:
      - php-fpm


  redis:
    image: redis:3.0
    ports:
      - "63791:6379"
#
#
#  node:
#    build:
#      context: ./
#      dockerfile: docker/node.docker
#    volumes:
#      - ./:/var/www
#    tty: true
#
#
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
      environment:
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
#        - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - ./storage/docker/elasticsearch:/usr/share/elasticsearch/data
      ports:
        - "9201:9200"
