version: '2'
services:
#---------------------------------------------------------------------------
#---------------------------------------------------------------------------
#---------------------------------------------------------------------------
  nginx:
    image: nginx:1.17.8
    ports:
#      - "8080:80"
     - "8080:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    links:
      - php-fpm
    networks:
      - inner
#---------------------------------------------------------------------------
#---------------------------------------------------------------------------
#---------------------------------------------------------------------------
  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/php-fpm.docker
    volumes:
      - ./:/var/www
      - ./docker/php-fpm/php-ini:/usr/local/etc/php/php.ini
    links:
      - mysql
      - redis
      - elasticsearch
    environment:
      - "XDEBUG_CONFIG=remote_host=192.168.220.1 remote_enable=1"
      - "PHP_IDE_CONFIG=serverName=docker_server"
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis"
      - "ELASTICSEARCH_HOST=elasticsearch:9200"
    networks:
      - inner
#---------------------------------------------------------------------------
#---------------------------------------------------------------------------
#---------------------------------------------------------------------------
  php-cli:
    build:
      context: ./
      dockerfile: docker/php-fpm/php-fpm.docker
    volumes:
      - ./:/var/www
      - ./docker/php-fpm/php-ini:/usr/local/etc/php/php.ini
    links:
      - mysql
      - redis
      - elasticsearch
    environment:
      - "XDEBUG_CONFIG=remote_host=192.168.220.1 remote_enable=1"
      - "PHP_IDE_CONFIG=serverName=docker_server"
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis"
      - "ELASTICSEARCH_HOST=elasticsearch:9200"
    networks:
      - inner
#---------------------------------------------------------------------------
#---------------------------------------------------------------------------
#---------------------------------------------------------------------------
  mysql:
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_DATABASE=app"
    ports:
      - "33061:3306"
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
    networks:
      - inner
#---------------------------------------------------------------------------
#---------------------------------------------------------------------------
#---------------------------------------------------------------------------
  redis:
    image: redis:3.0
    ports:
      - "63791:6379"
    networks:
      - inner
#---------------------------------------------------------------------------
#---------------------------------------------------------------------------
#---------------------------------------------------------------------------
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    #        - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./storage/docker/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9201:9200"
    networks:
      - inner
#---------------------------------------------------------------------------
#---------------------------------------------------------------------------
#---------------------------------------------------------------------------
  node:
    build:
      context: ./
      dockerfile: docker/node.docker
    volumes:
      - ./:/var/www
    tty: true
#---------------------------------------------------------------------------
#---------------------------------------------------------------------------
#---------------------------------------------------------------------------
networks:
  inner:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/24
